#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\QuranVerses\Index.cshtml"
    using QuranX.Persistence.Models;
    
    #line default
    #line hidden
    using QuranX.Web;
    
    #line 1 "..\..\Views\QuranVerses\Index.cshtml"
    using QuranX.Web.Models;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\QuranVerses\Index.cshtml"
    using QuranX.Web.Views.QuranVerses;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/QuranVerses/Index.cshtml")]
    public partial class _Views_QuranVerses_Index_cshtml : System.Web.Mvc.WebViewPage<ViewModel>
    {
        public _Views_QuranVerses_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\QuranVerses\Index.cshtml"
  
	ViewBag.Title = "The Noble Qur'an";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h1>");

            
            #line 10 "..\..\Views\QuranVerses\Index.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");

            
            #line 11 "..\..\Views\QuranVerses\Index.cshtml"
   Html.RenderPartial("SelectChapterAndVerse", Model.SelectChapterAndVerse); 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 12 "..\..\Views\QuranVerses\Index.cshtml"
 foreach (ChapterAndVerseSelection group in Model.DisplayVerses)
{

            
            #line default
            #line hidden
WriteLiteral("\t<h2>");

            
            #line 14 "..\..\Views\QuranVerses\Index.cshtml"
   Write(group.Chapter.EnglishName);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 14 "..\..\Views\QuranVerses\Index.cshtml"
                                Write(group.Chapter.ArabicName);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 15 "..\..\Views\QuranVerses\Index.cshtml"
	foreach (Verse verse in group.Verses)
	{

            
            #line default
            #line hidden
WriteLiteral("\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t<span");

WriteLiteral(" class=\"verse-reference\"");

WriteLiteral(">");

            
            #line 18 "..\..\Views\QuranVerses\Index.cshtml"
                                     Write(verse.ChapterNumber);

            
            #line default
            #line hidden
WriteLiteral(".");

            
            #line 18 "..\..\Views\QuranVerses\Index.cshtml"
                                                          Write(verse.VerseNumber);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 555), Tuple.Create("\"", 610)
, Tuple.Create(Tuple.Create("", 562), Tuple.Create("analysis/", 562), true)
            
            #line 19 "..\..\Views\QuranVerses\Index.cshtml"
, Tuple.Create(Tuple.Create("", 571), Tuple.Create<System.Object, System.Int32>(verse.ChapterNumber
            
            #line default
            #line hidden
, 571), false)
, Tuple.Create(Tuple.Create("", 591), Tuple.Create(".", 591), true)
            
            #line 19 "..\..\Views\QuranVerses\Index.cshtml"
, Tuple.Create(Tuple.Create("", 592), Tuple.Create<System.Object, System.Int32>(verse.VerseNumber
            
            #line default
            #line hidden
, 592), false)
);

WriteLiteral(">\r\n\t\t\t\t<dl");

WriteLiteral(" class=\"count-and-label\"");

WriteLiteral(">\r\n\t\t\t\t\t<dd>");

            
            #line 21 "..\..\Views\QuranVerses\Index.cshtml"
                   Write(verse.RootWordCount);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\t\t\t\t\t<dt>Roots</dt>\r\n\t\t\t\t</dl>\r\n\t\t\t</a>\r\n");

            
            #line 25 "..\..\Views\QuranVerses\Index.cshtml"
			
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\QuranVerses\Index.cshtml"
             if (verse.CommentaryCount > 0)
			{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 773), Tuple.Create("\"", 827)
, Tuple.Create(Tuple.Create("", 780), Tuple.Create("tafsirs/", 780), true)
            
            #line 27 "..\..\Views\QuranVerses\Index.cshtml"
, Tuple.Create(Tuple.Create("", 788), Tuple.Create<System.Object, System.Int32>(verse.ChapterNumber
            
            #line default
            #line hidden
, 788), false)
, Tuple.Create(Tuple.Create("", 808), Tuple.Create(".", 808), true)
            
            #line 27 "..\..\Views\QuranVerses\Index.cshtml"
, Tuple.Create(Tuple.Create("", 809), Tuple.Create<System.Object, System.Int32>(verse.VerseNumber
            
            #line default
            #line hidden
, 809), false)
);

WriteLiteral(">\r\n\t\t\t\t\t<dl");

WriteLiteral(" class=\"count-and-label\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<dd>");

            
            #line 29 "..\..\Views\QuranVerses\Index.cshtml"
                       Write(verse.CommentaryCount);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\t\t\t\t\t\t<dt>Tafirs</dt>\r\n\t\t\t\t\t</dl>\r\n\t\t\t\t</a>\r\n");

            
            #line 33 "..\..\Views\QuranVerses\Index.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

            
            #line 34 "..\..\Views\QuranVerses\Index.cshtml"
             if (verse.HadithCount > 0)
			{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 1000), Tuple.Create("\"", 1054)
, Tuple.Create(Tuple.Create("", 1007), Tuple.Create("hadiths/", 1007), true)
            
            #line 36 "..\..\Views\QuranVerses\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1015), Tuple.Create<System.Object, System.Int32>(verse.ChapterNumber
            
            #line default
            #line hidden
, 1015), false)
, Tuple.Create(Tuple.Create("", 1035), Tuple.Create(".", 1035), true)
            
            #line 36 "..\..\Views\QuranVerses\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1036), Tuple.Create<System.Object, System.Int32>(verse.VerseNumber
            
            #line default
            #line hidden
, 1036), false)
);

WriteLiteral(">\r\n\t\t\t\t\t<dl");

WriteLiteral(" class=\"count-and-label\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<dd>");

            
            #line 38 "..\..\Views\QuranVerses\Index.cshtml"
                       Write(verse.HadithCount);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\t\t\t\t\t\t<dt>Hadiths</dt>\r\n\t\t\t\t\t</dl>\r\n\t\t\t\t</a>\r\n");

            
            #line 42 "..\..\Views\QuranVerses\Index.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t</div>\r\n");

            
            #line 44 "..\..\Views\QuranVerses\Index.cshtml"
		foreach (VerseText translation in verse.VerseTexts)
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t<dl");

WriteLiteral(" class=\"boxed\"");

WriteLiteral(">\r\n\t\t\t<dt>");

            
            #line 47 "..\..\Views\QuranVerses\Index.cshtml"
           Write(translation.TranslatorName);

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n\t\t\t<dd>");

            
            #line 48 "..\..\Views\QuranVerses\Index.cshtml"
           Write(translation.Text);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\t\t</dl>\r\n");

            
            #line 50 "..\..\Views\QuranVerses\Index.cshtml"
		}
	}
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
