#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using QuranX.Web;
    
    #line 1 "..\..\Views\HadithIndex\BrowseHadithIndex.cshtml"
    using QuranX.Web.Views.HadithIndex;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/HadithIndex/BrowseHadithIndex.cshtml")]
    public partial class _Views_HadithIndex_BrowseHadithIndex_cshtml : System.Web.Mvc.WebViewPage<BrowseHadithIndexViewModel>
    {
        public _Views_HadithIndex_BrowseHadithIndex_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\HadithIndex\BrowseHadithIndex.cshtml"
  
	ViewBag.Title = $"{Model.HadithIndexHeaderViewModel.Collection.Name} Hadiths";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 8 "..\..\Views\HadithIndex\BrowseHadithIndex.cshtml"
Write(Html.Partial("HadithIndexHeader", Model.HadithIndexHeaderViewModel));

            
            #line default
            #line hidden
WriteLiteral("\r\n<ul");

WriteLiteral(" class=\"hadith-index__list\"");

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Views\HadithIndex\BrowseHadithIndex.cshtml"
	
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\HadithIndex\BrowseHadithIndex.cshtml"
     foreach (string nextValue in Model.NextReferencePartValueSelection)
	{

            
            #line default
            #line hidden
WriteLiteral("\t\t<li>\r\n\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 355), Tuple.Create("\"", 445)
            
            #line 13 "..\..\Views\HadithIndex\BrowseHadithIndex.cshtml"
, Tuple.Create(Tuple.Create("", 362), Tuple.Create<System.Object, System.Int32>(Model.HadithIndexHeaderViewModel.UrlSoFar
            
            #line default
            #line hidden
, 362), false)
, Tuple.Create(Tuple.Create("", 404), Tuple.Create("/", 404), true)
            
            #line 13 "..\..\Views\HadithIndex\BrowseHadithIndex.cshtml"
, Tuple.Create(Tuple.Create("", 405), Tuple.Create<System.Object, System.Int32>(Model.NextReferencePartName
            
            #line default
            #line hidden
, 405), false)
, Tuple.Create(Tuple.Create("", 433), Tuple.Create("-", 433), true)
            
            #line 13 "..\..\Views\HadithIndex\BrowseHadithIndex.cshtml"
              , Tuple.Create(Tuple.Create("", 434), Tuple.Create<System.Object, System.Int32>(nextValue
            
            #line default
            #line hidden
, 434), false)
, Tuple.Create(Tuple.Create("", 444), Tuple.Create("/", 444), true)
);

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 14 "..\..\Views\HadithIndex\BrowseHadithIndex.cshtml"
           Write(Model.NextReferencePartName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 14 "..\..\Views\HadithIndex\BrowseHadithIndex.cshtml"
                                        Write(nextValue);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</a>\r\n\t </li>\r\n");

            
            #line 17 "..\..\Views\HadithIndex\BrowseHadithIndex.cshtml"
	}

            
            #line default
            #line hidden
WriteLiteral("</ul>");

        }
    }
}
#pragma warning restore 1591
