#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using QuranX.Web;
    
    #line 1 "..\..\Views\HadithIndex\HadithIndexHeader.cshtml"
    using QuranX.Web.Views.HadithIndex;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/HadithIndex/HadithIndexHeader.cshtml")]
    public partial class _Views_HadithIndex_HadithIndexHeader_cshtml : System.Web.Mvc.WebViewPage<HadithIndexHeaderViewModel>
    {
        public _Views_HadithIndex_HadithIndexHeader_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<h1>Hadith collection</h1>\r\n<h2>\r\n\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 111), Tuple.Create("\"", 187)
, Tuple.Create(Tuple.Create("", 118), Tuple.Create("/Hadith/", 118), true)
            
            #line 6 "..\..\Views\HadithIndex\HadithIndexHeader.cshtml"
, Tuple.Create(Tuple.Create("", 126), Tuple.Create<System.Object, System.Int32>(Model.Collection.Code
            
            #line default
            #line hidden
, 126), false)
, Tuple.Create(Tuple.Create("", 148), Tuple.Create("/", 148), true)
            
            #line 6 "..\..\Views\HadithIndex\HadithIndexHeader.cshtml"
, Tuple.Create(Tuple.Create("", 149), Tuple.Create<System.Object, System.Int32>(Model.Collection.PrimaryReferenceCode
            
            #line default
            #line hidden
, 149), false)
);

WriteLiteral(">\r\n");

WriteLiteral("\t\t");

            
            #line 7 "..\..\Views\HadithIndex\HadithIndexHeader.cshtml"
   Write(Model.Collection.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</a>\r\n");

            
            #line 9 "..\..\Views\HadithIndex\HadithIndexHeader.cshtml"
	
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\HadithIndex\HadithIndexHeader.cshtml"
      
		string urlSoFar = $"/Hadith/{Model.Collection.Code}/{Model.Collection.PrimaryReferenceCode}/";
		foreach (string urlPart in Model.ReferencePartNamesAndValues)
		{
			urlSoFar += urlPart + "/";

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<span> / </span>");

WriteLiteral("<a");

WriteAttribute("href", Tuple.Create(" href=\"", 449), Tuple.Create("\"", 465)
            
            #line 14 "..\..\Views\HadithIndex\HadithIndexHeader.cshtml"
, Tuple.Create(Tuple.Create("", 456), Tuple.Create<System.Object, System.Int32>(urlSoFar
            
            #line default
            #line hidden
, 456), false)
);

WriteLiteral(">");

            
            #line 14 "..\..\Views\HadithIndex\HadithIndexHeader.cshtml"
                                           Write(urlPart);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 15 "..\..\Views\HadithIndex\HadithIndexHeader.cshtml"
		}
	
            
            #line default
            #line hidden
WriteLiteral("\r\n</h2>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
