#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using QuranX.Web;
    
    #line 1 "..\..\Views\HadithIndex\Hadiths.cshtml"
    using QuranX.Web.Views.HadithIndex;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/HadithIndex/Hadiths.cshtml")]
    public partial class _Views_HadithIndex_Hadiths_cshtml : System.Web.Mvc.WebViewPage<HadithsViewModel>
    {
        public _Views_HadithIndex_Hadiths_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\HadithIndex\Hadiths.cshtml"
  
    ViewBag.Title = $"{Model.HadithIndexHeaderViewModel.Collection.Name} Hadiths";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 8 "..\..\Views\HadithIndex\Hadiths.cshtml"
Write(Html.Partial("HadithIndexHeader", Model.HadithIndexHeaderViewModel));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 9 "..\..\Views\HadithIndex\Hadiths.cshtml"
 foreach (HadithViewModel hadithVM in Model.Hadiths)
{

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n");

            
            #line 12 "..\..\Views\HadithIndex\Hadiths.cshtml"
        
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\HadithIndex\Hadiths.cshtml"
         foreach (string text in hadithVM.Hadith.EnglishText)
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>");

            
            #line 14 "..\..\Views\HadithIndex\Hadiths.cshtml"
          Write(text);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 15 "..\..\Views\HadithIndex\Hadiths.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 16 "..\..\Views\HadithIndex\Hadiths.cshtml"
         foreach (string text in hadithVM.Hadith.ArabicText)
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>");

            
            #line 18 "..\..\Views\HadithIndex\Hadiths.cshtml"
          Write(text);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 19 "..\..\Views\HadithIndex\Hadiths.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

WriteLiteral("    <div>\r\n");

            
            #line 22 "..\..\Views\HadithIndex\Hadiths.cshtml"
        
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\HadithIndex\Hadiths.cshtml"
         foreach (KeyValuePair<string, string> reference in hadithVM.References)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"hadith__reference\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"hadith__reference-name\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 26 "..\..\Views\HadithIndex\Hadiths.cshtml"
               Write(reference.Key);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"hadith__reference-value\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 29 "..\..\Views\HadithIndex\Hadiths.cshtml"
               Write(reference.Value);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

            
            #line 32 "..\..\Views\HadithIndex\Hadiths.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 34 "..\..\Views\HadithIndex\Hadiths.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
