#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using QuranX.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/VerseAnalysis/VerseAnalysis.cshtml")]
    public partial class _Views_VerseAnalysis_VerseAnalysis_cshtml : System.Web.Mvc.WebViewPage<QuranX.Web.Views.VerseAnalysis.ViewModel>
    {
        public _Views_VerseAnalysis_VerseAnalysis_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
  
	ViewBag.Title = $"Analysis for Quran verse {Model.Chapter.ChapterNumber}.{Model.VerseNumber}";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h1>The Quran</h1>\r\n<h2>\r\n\tAnalysis of verse <a");

WriteAttribute("href", Tuple.Create(" href=\"", 204), Tuple.Create("\"", 259)
, Tuple.Create(Tuple.Create("", 211), Tuple.Create("/", 211), true)
            
            #line 9 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
, Tuple.Create(Tuple.Create("", 212), Tuple.Create<System.Object, System.Int32>(Model.Chapter.ChapterNumber
            
            #line default
            #line hidden
, 212), false)
, Tuple.Create(Tuple.Create("", 240), Tuple.Create(".", 240), true)
            
            #line 9 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
, Tuple.Create(Tuple.Create("", 241), Tuple.Create<System.Object, System.Int32>(Model.VerseNumber
            
            #line default
            #line hidden
, 241), false)
);

WriteLiteral(">\r\n");

WriteLiteral("\t\t");

            
            #line 10 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
   Write(Model.Chapter.ChapterNumber);

            
            #line default
            #line hidden
WriteLiteral(".");

            
            #line 10 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                                Write(Model.VerseNumber);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</a>\r\n</h2>\r\n<h3>\r\n");

WriteLiteral("\t");

            
            #line 14 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
Write(Model.Chapter.EnglishName);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 14 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                            Write(Model.Chapter.ArabicName);

            
            #line default
            #line hidden
WriteLiteral("\r\n</h3>\r\n");

            
            #line 16 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
   Html.RenderPartial("SelectChapterAndVerse", Model.SelectChapterAndVerse); 
            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t<ul");

WriteLiteral(" class=\"verse-analysis__word-list col-sm-11 col-md-10 col-lg-9 center striped\"");

WriteLiteral(">\r\n");

            
            #line 19 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
		
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
         foreach (var word in Model.VerseAnalysis.Words)
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<li");

WriteLiteral(" class=\"verse-analysis__word row\"");

WriteLiteral(">\r\n\t\t\t\t<a");

WriteAttribute("name", Tuple.Create(" name=\"", 687), Tuple.Create("\"", 715)
, Tuple.Create(Tuple.Create("", 694), Tuple.Create("word_", 694), true)
            
            #line 22 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
, Tuple.Create(Tuple.Create("", 699), Tuple.Create<System.Object, System.Int32>(word.WordNumber
            
            #line default
            #line hidden
, 699), false)
);

WriteLiteral("></a>\r\n\t\t\t\t<div");

WriteLiteral(" class=\"col-xs-4 col-sm-5 col-md-4 col-lg-2\"");

WriteLiteral(">\r\n\t\t\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 785), Tuple.Create("\"", 840)
, Tuple.Create(Tuple.Create("", 792), Tuple.Create("/", 792), true)
            
            #line 24 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
, Tuple.Create(Tuple.Create("", 793), Tuple.Create<System.Object, System.Int32>(Model.Chapter.ChapterNumber
            
            #line default
            #line hidden
, 793), false)
, Tuple.Create(Tuple.Create("", 821), Tuple.Create(".", 821), true)
            
            #line 24 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
, Tuple.Create(Tuple.Create("", 822), Tuple.Create<System.Object, System.Int32>(Model.VerseNumber
            
            #line default
            #line hidden
, 822), false)
);

WriteLiteral(">\r\n\t\t\t\t\t\t<span");

WriteLiteral(" class=\"verse__reference\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 26 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                       Write(Model.Chapter.ChapterNumber);

            
            #line default
            #line hidden
WriteLiteral(".");

            
            #line 26 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                                                    Write(Model.VerseNumber);

            
            #line default
            #line hidden
WriteLiteral(".");

            
            #line 26 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                                                                       Write(word.WordNumber);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t</span>\r\n\t\t\t\t\t</a>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div");

WriteLiteral(" class=\"col-xs-8 col-sm-7 col-md-8 col-lg-10 verse-analysis__word-image\"");

WriteLiteral(">\r\n\t\t\t\t\t<img");

WriteAttribute("src", Tuple.Create(" src=\"", 1086), Tuple.Create("\"", 1162)
, Tuple.Create(Tuple.Create("", 1092), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Images/ArabicWords/")
, 1092), false)
            
            #line 31 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
, Tuple.Create(Tuple.Create("", 1121), Tuple.Create<System.Object, System.Int32>(Html.GetHexValues(word.Buckwalter)
            
            #line default
            #line hidden
, 1121), false)
, Tuple.Create(Tuple.Create("", 1158), Tuple.Create(".png", 1158), true)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 1163), Tuple.Create("\"", 1185)
            
            #line 31 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                           , Tuple.Create(Tuple.Create("", 1169), Tuple.Create<System.Object, System.Int32>(word.Buckwalter
            
            #line default
            #line hidden
, 1169), false)
);

WriteLiteral(" />\r\n\t\t\t\t</div>\r\n\t\t\t\t<div");

WriteLiteral(" class=\"col-xs-12 col-sm-5 col-md-4 col-lg-2 verse-analysis__word-text\"");

WriteLiteral(">\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"verse-analysis__word-text-buckwalter\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 35 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                   Write(word.Buckwalter);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"verse-analysis__word-text-english\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 38 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                   Write(word.English);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t\t<ol");

WriteLiteral(" class=\"col-xs-12 col-sm-7 col-md-8 col-lg-10 col verse-analysis__word-part-list\"" +
"");

WriteLiteral(">\r\n");

            
            #line 42 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
					
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                     foreach (var wordPart in word.WordParts)
					{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t<li");

WriteLiteral(" class=\"verse-analysis__word-part\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 45 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                       Write(wordPart.Type);

            
            #line default
            #line hidden
WriteLiteral(" -\r\n");

            
            #line 46 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
							
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                             foreach (string decorator in @wordPart.Decorators)
							{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t<span>");

            
            #line 48 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                                 Write(decorator);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 49 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
							}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 50 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                       Write(wordPart.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 51 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
							
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                             if (!string.IsNullOrEmpty(wordPart.Root))
							{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t<span");

WriteLiteral(" class=\"arabicText\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t");

            
            #line 54 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                               Write(Html.RouteLink(
										linkText: wordPart.Root,
										routeName: "RootAnalysis",
										routeValues: new
										{
											RootLetterNames = QuranX.Web.ArabicHelper
												.ArabicToLetterNames(wordPart.Root)
										}
									));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t</span>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t<span>(");

            
            #line 64 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
                                  Write(QuranX.Web.ArabicHelper.ArabicToLetterNames(wordPart.Root));

            
            #line default
            #line hidden
WriteLiteral(")</span>\r\n");

            
            #line 65 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
							}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t</li>\r\n");

            
            #line 67 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
					}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t</ol>\r\n\t\t\t</li>\r\n");

            
            #line 70 "..\..\Views\VerseAnalysis\VerseAnalysis.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\t</ul>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
