#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using QuranX.Web;
    
    #line 2 "..\..\Views\Search\Search.cshtml"
    using QuranX.Web.Views.Search;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Search/Search.cshtml")]
    public partial class _Views_Search_Search_cshtml : System.Web.Mvc.WebViewPage<QuranX.Web.Views.Search.ViewModel>
    {
        public _Views_Search_Search_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Search\Search.cshtml"
  
	ViewBag.Title = "Search";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h1>Search</h1>\r\n");

            
            #line 8 "..\..\Views\Search\Search.cshtml"
 using (Html.BeginForm(actionName: "index", controllerName: "Search", method: FormMethod.Get))
{

            
            #line default
            #line hidden
WriteLiteral("\t<div");

WriteLiteral(" class=\"search__criteria\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t");

            
            #line 12 "..\..\Views\Search\Search.cshtml"
       Write(Html.TextBoxFor(x => x.Q, new { @class = "form-control search__criteria-text center", placeholder = "Search..." }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t</div>\r\n\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t");

            
            #line 15 "..\..\Views\Search\Search.cshtml"
       Write(Html.DropDownListFor(x => x.Context, Model.Context, new { @class = "form-control col-xs-12 center" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t</div>\r\n\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t<input");

WriteLiteral(" class=\"btn btn-primary center\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(" />\r\n\t\t</div>\r\n\t</div>\r\n");

            
            #line 21 "..\..\Views\Search\Search.cshtml"
}

            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Search\Search.cshtml"
 if (Model.SearchResults != null)
{
	string resultsCaption = Model.SearchResults.Count() == 1 ? "result" : "results";
	int resultNumber = 0;

            
            #line default
            #line hidden
WriteLiteral("\t<h2>");

            
            #line 26 "..\..\Views\Search\Search.cshtml"
   Write(Model.SearchResults.Count());

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 26 "..\..\Views\Search\Search.cshtml"
                                Write(resultsCaption);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 27 "..\..\Views\Search\Search.cshtml"


            
            #line default
            #line hidden
WriteLiteral("\t<div");

WriteLiteral(" class=\"search__results\"");

WriteLiteral(">\r\n");

            
            #line 29 "..\..\Views\Search\Search.cshtml"
		
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Search\Search.cshtml"
         foreach (SearchResultWithLink searchResult in Model.SearchResults)
		{
			resultNumber++;

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<dl");

WriteLiteral(" class=\"search__item\"");

WriteLiteral(">\r\n\t\t\t\t<dt>\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 34 "..\..\Views\Search\Search.cshtml"
               Write(resultNumber);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 1064), Tuple.Create("\"", 1088)
            
            #line 35 "..\..\Views\Search\Search.cshtml"
, Tuple.Create(Tuple.Create("", 1071), Tuple.Create<System.Object, System.Int32>(searchResult.Url
            
            #line default
            #line hidden
, 1071), false)
);

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 36 "..\..\Views\Search\Search.cshtml"
                   Write(searchResult.Caption);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</a>\r\n\t\t\t\t</dt>\r\n\t\t\t\t<dd>\r\n\t\t\t\t\t<ul>\r\n");

            
            #line 41 "..\..\Views\Search\Search.cshtml"
						
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Search\Search.cshtml"
                         foreach (var snippet in searchResult.Snippets)
						{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t<li>");

            
            #line 43 "..\..\Views\Search\Search.cshtml"
                           Write(Html.Highlight(snippet));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 44 "..\..\Views\Search\Search.cshtml"
						}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t</ul>\r\n\t\t\t\t</dd>\r\n\t\t\t</dl>\r\n");

            
            #line 48 "..\..\Views\Search\Search.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\t</div>\r\n");

            
            #line 50 "..\..\Views\Search\Search.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
