//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuranX.DocumentModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuranX.DocumentModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///
        ///# PLEASE DO NOT REMOVE OR CHANGE THIS COPYRIGHT BLOCK
        ///#====================================================================
        ///#
        ///#  Tanzil Quran Text (Uthmani, version 1.0.2)
        ///#  Copyright (C) 2008-2010 Tanzil.net
        ///#  License: Creative Commons Attribution 3.0
        ///#
        ///#  This copy of quran text is carefully produced, highly 
        ///#  verified and continuously monitored by a group of specialists 
        ///#  at Tanzil project.
        ///#
        ///#  TERMS OF USE:
        ///#
        ///#  - Permission is granted [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quran_uthmani {
            get {
                return ResourceManager.GetString("quran_uthmani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;quran&gt;
        ///  &lt;chapter index=&quot;1&quot; name=&quot;Al Fatiha (The opening)&quot; period=&quot;Makka&quot; verses=&quot;7&quot; /&gt;
        ///  &lt;chapter index=&quot;2&quot; name=&quot;Al Baqara (The cow)&quot; period=&quot;Madina&quot; verses=&quot;286&quot; /&gt;
        ///  &lt;chapter index=&quot;3&quot; name=&quot;Al Imran (The family of Imran)&quot; period=&quot;Madina&quot; verses=&quot;200&quot; /&gt;
        ///  &lt;chapter index=&quot;4&quot; name=&quot;An Nisa (The women)&quot; period=&quot;Madina&quot; verses=&quot;176&quot; /&gt;
        ///  &lt;chapter index=&quot;5&quot; name=&quot;Al Maida (The food)&quot; period=&quot;Madina&quot; verses=&quot;120&quot; /&gt;
        ///  &lt;chapter index=&quot;6&quot; name=&quot;Al Anam (Cattle)&quot; p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuranStructure {
            get {
                return ResourceManager.GetString("QuranStructure", resourceCulture);
            }
        }
    }
}
