#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\HadithView.cshtml"
    using QuranX.Shared.Models;
    
    #line default
    #line hidden
    using QuranX.Web;
    
    #line 2 "..\..\Views\Shared\HadithView.cshtml"
    using QuranX.Web.Views.Shared;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/HadithView.cshtml")]
    public partial class _Views_Shared_HadithView_cshtml : System.Web.Mvc.WebViewPage<QuranX.Web.Views.Shared.HadithViewModel>
    {
        public _Views_Shared_HadithView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"hadith\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"hadith__references\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"hadith__reference\"");

WriteLiteral(">\r\n\t\t\t<div");

WriteLiteral(" class=\"hadith__reference-name\"");

WriteLiteral(">\r\n\t\t\t\tCollection\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteral(" class=\"hadith__reference-value\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 12 "..\..\Views\Shared\HadithView.cshtml"
           Write(Model.CollectionName);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</div>\r\n\t\t</div>\r\n");

            
            #line 15 "..\..\Views\Shared\HadithView.cshtml"
		
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\HadithView.cshtml"
         foreach (HadithReferenceViewModel reference in @Model.References)
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<div");

WriteLiteral(" class=\"hadith__reference\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"hadith__reference-name\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 19 "..\..\Views\Shared\HadithView.cshtml"
               Write(reference.IndexName);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t</div>\r\n\t\t\t\t<div");

WriteLiteral(" class=\"hadith__reference-value\"");

WriteLiteral(">\r\n\t\t\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 603), Tuple.Create("\"", 687)
, Tuple.Create(Tuple.Create("", 610), Tuple.Create("/Hadith/", 610), true)
            
            #line 22 "..\..\Views\Shared\HadithView.cshtml"
, Tuple.Create(Tuple.Create("", 618), Tuple.Create<System.Object, System.Int32>(reference.CollectionCode
            
            #line default
            #line hidden
, 618), false)
, Tuple.Create(Tuple.Create("", 643), Tuple.Create("/", 643), true)
            
            #line 22 "..\..\Views\Shared\HadithView.cshtml"
, Tuple.Create(Tuple.Create("", 644), Tuple.Create<System.Object, System.Int32>(reference.IndexCode
            
            #line default
            #line hidden
, 644), false)
, Tuple.Create(Tuple.Create("", 664), Tuple.Create("/", 664), true)
            
            #line 22 "..\..\Views\Shared\HadithView.cshtml"
     , Tuple.Create(Tuple.Create("", 665), Tuple.Create<System.Object, System.Int32>(reference.ToUrlPath()
            
            #line default
            #line hidden
, 665), false)
);

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 23 "..\..\Views\Shared\HadithView.cshtml"
                   Write(reference.ToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</a>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n");

            
            #line 27 "..\..\Views\Shared\HadithView.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\t\t");

            
            #line 28 "..\..\Views\Shared\HadithView.cshtml"
         if (Model.Hadith.VerseRangeReferences.Any())
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<div");

WriteLiteral(" class=\"hadith__verse-references\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"hadith__reference-verse-caption\"");

WriteLiteral(">\r\n\t\t\t\t\tRelated Qur\'an verses\r\n\t\t\t\t</div>\r\n\t\t\t\t<ul");

WriteLiteral(" class=\"hadith__reference-verse-numbers\"");

WriteLiteral(">\r\n");

            
            #line 35 "..\..\Views\Shared\HadithView.cshtml"
					
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Shared\HadithView.cshtml"
                     foreach (VerseRangeReference verse in Model.Hadith.VerseRangeReferences)
					{
						string verseAsString = verse.Chapter + "." + verse.FirstVerse;
						if (verse.IsMultipleVerses())
						{
							verseAsString += "-" + verse.LastVerse;
						}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 1279), Tuple.Create("\"", 1301)
, Tuple.Create(Tuple.Create("", 1286), Tuple.Create("/", 1286), true)
            
            #line 43 "..\..\Views\Shared\HadithView.cshtml"
, Tuple.Create(Tuple.Create("", 1287), Tuple.Create<System.Object, System.Int32>(verseAsString
            
            #line default
            #line hidden
, 1287), false)
);

WriteLiteral(">");

            
            #line 43 "..\..\Views\Shared\HadithView.cshtml"
                                                 Write(verseAsString);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\t\t\t\t\t\t</li>\r\n");

            
            #line 45 "..\..\Views\Shared\HadithView.cshtml"
					}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t</ul>\r\n\t\t\t</div>\r\n");

            
            #line 48 "..\..\Views\Shared\HadithView.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\t</div>\r\n\t<div");

WriteLiteral(" class=\"hadith__text\"");

WriteLiteral(">\r\n");

            
            #line 51 "..\..\Views\Shared\HadithView.cshtml"
		
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Shared\HadithView.cshtml"
         foreach (string text in @Model.Hadith.EnglishText)
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<p");

WriteLiteral(" class=\"highlightable\"");

WriteLiteral(">");

            
            #line 53 "..\..\Views\Shared\HadithView.cshtml"
                                Write(text);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 54 "..\..\Views\Shared\HadithView.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\t</div>\r\n\t<div");

WriteLiteral(" class=\"hadith__text arabic\"");

WriteLiteral(">\r\n");

            
            #line 57 "..\..\Views\Shared\HadithView.cshtml"
		
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Shared\HadithView.cshtml"
         foreach (string text in @Model.Hadith.ArabicText)
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<p");

WriteLiteral(" class=\"highlightable\"");

WriteLiteral(">");

            
            #line 59 "..\..\Views\Shared\HadithView.cshtml"
                                Write(text);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 60 "..\..\Views\Shared\HadithView.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\t</div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
