#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using QuranX.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/HadithView.cshtml")]
    public partial class _Views_Shared_HadithView_cshtml : System.Web.Mvc.WebViewPage<QuranX.Web.Views.Shared.HadithViewModel>
    {
        public _Views_Shared_HadithView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"hadith\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"hadith__references\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"hadith__reference\"");

WriteLiteral(">\r\n\t\t\t<div");

WriteLiteral(" class=\"hadith__reference-name\"");

WriteLiteral(">\r\n\t\t\t\tCollection\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteral(" class=\"hadith__reference-value\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 10 "..\..\Views\Shared\HadithView.cshtml"
           Write(Model.CollectionName);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</div>\r\n\t\t</div>\r\n");

            
            #line 13 "..\..\Views\Shared\HadithView.cshtml"
		
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Shared\HadithView.cshtml"
         foreach (KeyValuePair<string, string> reference in @Model.References)
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<div");

WriteLiteral(" class=\"hadith__reference\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"hadith__reference-name\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 17 "..\..\Views\Shared\HadithView.cshtml"
               Write(reference.Key);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t</div>\r\n\t\t\t\t<div");

WriteLiteral(" class=\"hadith__reference-value\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 20 "..\..\Views\Shared\HadithView.cshtml"
               Write(reference.Value);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n");

            
            #line 23 "..\..\Views\Shared\HadithView.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\t</div>\r\n\t<div");

WriteLiteral(" class=\"hadith__text\"");

WriteLiteral(">\r\n");

            
            #line 26 "..\..\Views\Shared\HadithView.cshtml"
		
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\HadithView.cshtml"
         foreach (string text in @Model.Hadith.EnglishText)
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<p>");

            
            #line 28 "..\..\Views\Shared\HadithView.cshtml"
          Write(text);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 29 "..\..\Views\Shared\HadithView.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\t</div>\r\n\t<div");

WriteLiteral(" class=\"hadith__text arabic\"");

WriteLiteral(">\r\n");

            
            #line 32 "..\..\Views\Shared\HadithView.cshtml"
		
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Shared\HadithView.cshtml"
         foreach (string text in @Model.Hadith.ArabicText)
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<p>");

            
            #line 34 "..\..\Views\Shared\HadithView.cshtml"
          Write(text);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 35 "..\..\Views\Shared\HadithView.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\t</div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
