#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using QuranX.Web;
    
    #line 1 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
    using QuranX.Web.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/SelectChapterAndVerse.cshtml")]
    public partial class _Views_Shared_SelectChapterAndVerse_cshtml : System.Web.Mvc.WebViewPage<SelectChapterAndVerse>
    {
        public _Views_Shared_SelectChapterAndVerse_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"chapter-and-verse-selector\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-xs-3 col-sm-1\"");

WriteLiteral(">\r\n\t\t\t<label");

WriteLiteral(" for=\"ChapterNumber\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">Chapter</label>\r\n\t\t</div>\r\n\t\t<div");

WriteLiteral(" class=\"col-xs-9 col-sm-5\"");

WriteLiteral(">\r\n\t\t\t<select");

WriteLiteral(" id=\"ChapterNumber\"");

WriteLiteral(" name=\"ChapterNumber\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n");

            
            #line 11 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
				
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
                 if (!Model.AllVerses)
				{
					foreach (ChapterAndVerseReferenceSelection item in Model.AvailableChapters)
					{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t<option");

WriteAttribute("value", Tuple.Create(" value=\"", 481), Tuple.Create("\"", 516)
            
            #line 15 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
, Tuple.Create(Tuple.Create("", 489), Tuple.Create<System.Object, System.Int32>(item.Chapter.ChapterNumber
            
            #line default
            #line hidden
, 489), false)
);

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 16 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
                       Write(item.Chapter.ChapterNumber);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 16 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
                                                     Write(item.Chapter.EnglishName);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t</option>\r\n");

            
            #line 18 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
					}
				}
				else
				{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"1\"");

WriteLiteral(">\r\n\t\t\t\t\t\t1 - Al Fatiha (The opening)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"2\"");

WriteLiteral(">\r\n\t\t\t\t\t\t2 - Al Baqara (The cow)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"3\"");

WriteLiteral(">\r\n\t\t\t\t\t\t3 - Al Imran (The family of Imran)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"4\"");

WriteLiteral(">\r\n\t\t\t\t\t\t4 - An Nisa (The women)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"5\"");

WriteLiteral(">\r\n\t\t\t\t\t\t5 - Al Maida (The food)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t6 - Al Anam (Cattle)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"7\"");

WriteLiteral(">\r\n\t\t\t\t\t\t7 - Al Araf (The heights)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"8\"");

WriteLiteral(">\r\n\t\t\t\t\t\t8 - Al Anfal (Spoils of war)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"9\"");

WriteLiteral(">\r\n\t\t\t\t\t\t9 - Al Tawba (Immunity)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"10\"");

WriteLiteral(">\r\n\t\t\t\t\t\t10 - Yunus (Jonah)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"11\"");

WriteLiteral(">\r\n\t\t\t\t\t\t11 - Hud\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"12\"");

WriteLiteral(">\r\n\t\t\t\t\t\t12 - Yusuf (Joseph)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"13\"");

WriteLiteral(">\r\n\t\t\t\t\t\t13 - Ar Rad (The thunder)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"14\"");

WriteLiteral(">\r\n\t\t\t\t\t\t14 - Ibrahim (Abraham)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"15\"");

WriteLiteral(">\r\n\t\t\t\t\t\t15 - Al Hijr (The rock)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"16\"");

WriteLiteral(">\r\n\t\t\t\t\t\t16 - An Nahl (The bee)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"17\"");

WriteLiteral(">\r\n\t\t\t\t\t\t17 - Bani Israil (The Israelites)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"18\"");

WriteLiteral(">\r\n\t\t\t\t\t\t18 - Al Kahf (The cave)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"19\"");

WriteLiteral(">\r\n\t\t\t\t\t\t19 - Maryamn (Mary)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"20\"");

WriteLiteral(">\r\n\t\t\t\t\t\t20 - Ta-Ha\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"21\"");

WriteLiteral(">\r\n\t\t\t\t\t\t21 - Al Anbiya (The prophets)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"22\"");

WriteLiteral(">\r\n\t\t\t\t\t\t22 - Al Hajj (The pilgrimage)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"23\"");

WriteLiteral(">\r\n\t\t\t\t\t\t23 - Al Muminun (The believers)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"24\"");

WriteLiteral(">\r\n\t\t\t\t\t\t24 - An Nur (The light)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"25\"");

WriteLiteral(">\r\n\t\t\t\t\t\t25 - Al Furqan (The discrimination)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"26\"");

WriteLiteral(">\r\n\t\t\t\t\t\t26 - Ash Shuara (The poets)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"27\"");

WriteLiteral(">\r\n\t\t\t\t\t\t27 - An Naml (The ant)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"28\"");

WriteLiteral(">\r\n\t\t\t\t\t\t28 - Al Qasas (The narrative)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"29\"");

WriteLiteral(">\r\n\t\t\t\t\t\t29 - Al Ankabut (The spider)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"30\"");

WriteLiteral(">\r\n\t\t\t\t\t\t30 - Ar Rum (The Romans)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"31\"");

WriteLiteral(">\r\n\t\t\t\t\t\t31 - Luqman\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"32\"");

WriteLiteral(">\r\n\t\t\t\t\t\t32 - As Sajda (The adoration)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"33\"");

WriteLiteral(">\r\n\t\t\t\t\t\t33 - Al Ahzab (The allies)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"34\"");

WriteLiteral(">\r\n\t\t\t\t\t\t34 - Al Saba (The Saba)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"35\"");

WriteLiteral(">\r\n\t\t\t\t\t\t35 - Al Fatir (The angels)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"36\"");

WriteLiteral(">\r\n\t\t\t\t\t\t36 - Ya Sin\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"37\"");

WriteLiteral(">\r\n\t\t\t\t\t\t37 - As Saffat (Those who set up ranks)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"38\"");

WriteLiteral(">\r\n\t\t\t\t\t\t38 - Saad\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"39\"");

WriteLiteral(">\r\n\t\t\t\t\t\t39 - Az Zumar (The troops)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"40\"");

WriteLiteral(">\r\n\t\t\t\t\t\t40 - Al Ghafir (The forgiver)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"41\"");

WriteLiteral(">\r\n\t\t\t\t\t\t41 - Fussilat (Explained in detail)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"42\"");

WriteLiteral(">\r\n\t\t\t\t\t\t42 - Ash Shura (The council)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"43\"");

WriteLiteral(">\r\n\t\t\t\t\t\t43 - Az Zukhruf (Gold)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"44\"");

WriteLiteral(">\r\n\t\t\t\t\t\t44 - Ad Dukhan (Drought)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"45\"");

WriteLiteral(">\r\n\t\t\t\t\t\t45 - Al Jathiya (Kneeling)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"46\"");

WriteLiteral(">\r\n\t\t\t\t\t\t46 - Al Ahqaf (The dunes)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"47\"");

WriteLiteral(">\r\n\t\t\t\t\t\t47 - Muhammad\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"48\"");

WriteLiteral(">\r\n\t\t\t\t\t\t48 - Al Fath (Victory)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"49\"");

WriteLiteral(">\r\n\t\t\t\t\t\t49 - Al Hujraat (The apartments)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"50\"");

WriteLiteral(">\r\n\t\t\t\t\t\t50 - Qaf\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"51\"");

WriteLiteral(">\r\n\t\t\t\t\t\t51 - Adh Dhariyat (The scatterers)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"52\"");

WriteLiteral(">\r\n\t\t\t\t\t\t52 - At Tur (The mount)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"53\"");

WriteLiteral(">\r\n\t\t\t\t\t\t53 - An Najm (The star)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"54\"");

WriteLiteral(">\r\n\t\t\t\t\t\t54 - Al Qamar (The Moon)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"55\"");

WriteLiteral(">\r\n\t\t\t\t\t\t55 - Ar Rahman (The beneficent)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"56\"");

WriteLiteral(">\r\n\t\t\t\t\t\t56 - Al Waqia (The event)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"57\"");

WriteLiteral(">\r\n\t\t\t\t\t\t57 - Al Hadid (Iron)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"58\"");

WriteLiteral(">\r\n\t\t\t\t\t\t58 - Al Mujadila (The pleading woman)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"59\"");

WriteLiteral(">\r\n\t\t\t\t\t\t59 - Al Hashr (Exile)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"60\"");

WriteLiteral(">\r\n\t\t\t\t\t\t60 - Al Mumtahana (The examined woman)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"61\"");

WriteLiteral(">\r\n\t\t\t\t\t\t61 - As Saff (The ranks)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"62\"");

WriteLiteral(">\r\n\t\t\t\t\t\t62 - Al Jumua (The congregation)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"63\"");

WriteLiteral(">\r\n\t\t\t\t\t\t63 - Al Munafiqun (The hypocrites)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"64\"");

WriteLiteral(">\r\n\t\t\t\t\t\t64 - At Taghabun (Manifestation of losses)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"65\"");

WriteLiteral(">\r\n\t\t\t\t\t\t65 - At Talaq (Divorce)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"66\"");

WriteLiteral(">\r\n\t\t\t\t\t\t66 - At Tahrim (Prohibition)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"67\"");

WriteLiteral(">\r\n\t\t\t\t\t\t67 - Al Mulk (The kingdom)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"68\"");

WriteLiteral(">\r\n\t\t\t\t\t\t68 - Al Qalam (The pen)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"69\"");

WriteLiteral(">\r\n\t\t\t\t\t\t69 - Al Haqqa (The reality)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"70\"");

WriteLiteral(">\r\n\t\t\t\t\t\t70 - Al Maarij (Ascending stairways)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"71\"");

WriteLiteral(">\r\n\t\t\t\t\t\t71 - Nuh (Noah)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"72\"");

WriteLiteral(">\r\n\t\t\t\t\t\t72 - Al Jinn (The Jinn)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"73\"");

WriteLiteral(">\r\n\t\t\t\t\t\t73 - Al Muzzammil (The enshrouded one)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"74\"");

WriteLiteral(">\r\n\t\t\t\t\t\t74 - Al Muddaththir (The cloaked one)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"75\"");

WriteLiteral(">\r\n\t\t\t\t\t\t75 - Al Qiyama (Resurrection)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"76\"");

WriteLiteral(">\r\n\t\t\t\t\t\t76 - Al Insan (Man)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"77\"");

WriteLiteral(">\r\n\t\t\t\t\t\t77 - Al Mursalat (The emissaries)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"78\"");

WriteLiteral(">\r\n\t\t\t\t\t\t78 - An Naba (The tidings)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"79\"");

WriteLiteral(">\r\n\t\t\t\t\t\t79 - An Naziat (Those who yearn)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"80\"");

WriteLiteral(">\r\n\t\t\t\t\t\t80 - Abasa (He frowned)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"81\"");

WriteLiteral(">\r\n\t\t\t\t\t\t81 - At Takwir (The folding up)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"82\"");

WriteLiteral(">\r\n\t\t\t\t\t\t82 - Al Infitar (The cleaving)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"83\"");

WriteLiteral(">\r\n\t\t\t\t\t\t83 - Al Mutaffifin (The cheats)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"84\"");

WriteLiteral(">\r\n\t\t\t\t\t\t84 - Al Isnhiqaq (Splitting open)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"85\"");

WriteLiteral(">\r\n\t\t\t\t\t\t85 - Al Buruj (The stars)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"86\"");

WriteLiteral(">\r\n\t\t\t\t\t\t86 - At Tariq (The morning star)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"87\"");

WriteLiteral(">\r\n\t\t\t\t\t\t87 - Al Ala (The most high)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"88\"");

WriteLiteral(">\r\n\t\t\t\t\t\t88 - Al Ghashiya (The overwhelming)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"89\"");

WriteLiteral(">\r\n\t\t\t\t\t\t89 - Al Fajr (The dawn)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"90\"");

WriteLiteral(">\r\n\t\t\t\t\t\t90 - Al Balad (The city)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"91\"");

WriteLiteral(">\r\n\t\t\t\t\t\t91 - Ash Shams (The Sun)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"92\"");

WriteLiteral(">\r\n\t\t\t\t\t\t92 - Al Lail (The night)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"93\"");

WriteLiteral(">\r\n\t\t\t\t\t\t93 - Ad Duhaa (The brightness of day)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"94\"");

WriteLiteral(">\r\n\t\t\t\t\t\t94 - Al Inshirah (The expansion)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"95\"");

WriteLiteral(">\r\n\t\t\t\t\t\t95 - At tin (The fig)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"96\"");

WriteLiteral(">\r\n\t\t\t\t\t\t96 - Al Alaq (The clot)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"97\"");

WriteLiteral(">\r\n\t\t\t\t\t\t97 - Al Qadr (The power)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"98\"");

WriteLiteral(">\r\n\t\t\t\t\t\t98 - Al Bayyina (Clear proof)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"99\"");

WriteLiteral(">\r\n\t\t\t\t\t\t99 - Al Zalzala (The shaking)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"100\"");

WriteLiteral(">\r\n\t\t\t\t\t\t100 - Al Adiyat (The assaulters)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"101\"");

WriteLiteral(">\r\n\t\t\t\t\t\t101 - Al Qaria (The calamity)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"102\"");

WriteLiteral(">\r\n\t\t\t\t\t\t102 - At Takathur (Abundance of wealth)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"103\"");

WriteLiteral(">\r\n\t\t\t\t\t\t103 - Al Asr (The time)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"104\"");

WriteLiteral(">\r\n\t\t\t\t\t\t104 - Al Humaza (The slanderer)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"105\"");

WriteLiteral(">\r\n\t\t\t\t\t\t105 - Al Fil (The elephant)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"106\"");

WriteLiteral(">\r\n\t\t\t\t\t\t106 - Quraish (The Quraish)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"107\"");

WriteLiteral(">\r\n\t\t\t\t\t\t107 - Al Maun (Almsgiving)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"108\"");

WriteLiteral(">\r\n\t\t\t\t\t\t108 - Al Kauthar (Abundance)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"109\"");

WriteLiteral(">\r\n\t\t\t\t\t\t109 - Al Kafirun (The disbelievers)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"110\"");

WriteLiteral(">\r\n\t\t\t\t\t\t110 - An Nasr (Divine support)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"111\"");

WriteLiteral(">\r\n\t\t\t\t\t\t111 - Al Lahab (The flame)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"112\"");

WriteLiteral(">\r\n\t\t\t\t\t\t112 - Al Ikhlas (The unity)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"113\"");

WriteLiteral(">\r\n\t\t\t\t\t\t113 - Al Falaq (Dawn)\r\n\t\t\t\t\t</option>\r\n");

WriteLiteral("\t\t\t\t\t<option");

WriteLiteral(" value=\"114\"");

WriteLiteral(">\r\n\t\t\t\t\t\t114 - An Nas (Mankind)\r\n\t\t\t\t\t</option>\r\n");

            
            #line 364 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
				}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t</select>\r\n\t\t</div>\r\n\t\t<div");

WriteLiteral(" class=\"col-xs-3 col-sm-1\"");

WriteLiteral(">\r\n\t\t\t<label");

WriteLiteral(" for=\"VerseNumber\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">Verse</label>\r\n\t\t</div>\r\n\t\t<div");

WriteLiteral(" class=\"col-xs-6 col-sm-5\"");

WriteLiteral(">\r\n\t\t\t<select");

WriteLiteral(" id=\"VerseNumber\"");

WriteLiteral(" name=\"VerseNumber\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral("></select>\r\n\t\t</div>\r\n\t</div>\r\n\t<div");

WriteLiteral(" class=\"chapter-and-verse-selector__navigator row\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"chapter-and-verse-selector__navigator-buttons btn-group\"");

WriteLiteral(" role=\"group\"");

WriteLiteral(">\r\n\t\t\t<button");

WriteLiteral(" id=\"SelectPreviousVerseNavigateButton\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" class=\"btn\"");

WriteLiteral(">&laquo; Prev</button>\r\n\t\t\t<button");

WriteLiteral(" id=\"SelectChapterAndVerseNavigateButton\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" class=\"btn\"");

WriteLiteral(">Go</button>\r\n\t\t\t<button");

WriteLiteral(" id=\"SelectNextVerseNavigateButton\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" class=\"btn\"");

WriteLiteral(">Next &raquo;</button>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r\n\r\n<script>\r\n\t(function () {\r\n\t" +
"\tvar selectedChapterNumber = ");

            
            #line 385 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
                               Write(Model.SelectedChapterNumber);

            
            #line default
            #line hidden
WriteLiteral(";\r\n\t\tvar selectedVerseNumber = ");

            
            #line 386 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
                             Write(Model.SelectedVerseNumber);

            
            #line default
            #line hidden
WriteLiteral(";\r\n\r\n\t\tvar chapterNumberElement = $(\"#ChapterNumber\");\r\n\t\tvar verseNumberElement " +
"= $(\"#VerseNumber\");\r\n\r\n");

            
            #line 391 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
		
            
            #line default
            #line hidden
            
            #line 391 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
         if (!Model.AllVerses)
		{
			// JavaScript

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("var versesForChapter = {};\r\n");

WriteLiteral("\t\t\t");

WriteLiteral("for (chapterNumber = 1; chapterNumber <= 114; chapterNumber++)\r\n");

WriteLiteral("\t\t\t");

WriteLiteral("{\r\n");

WriteLiteral("\t\t\t\t");

WriteLiteral("versesForChapter[chapterNumber] = [];\r\n");

WriteLiteral("\t\t\t");

WriteLiteral("}\r\n");

            
            #line 399 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"

			foreach (ChapterAndVerseReferenceSelection item in Model.AvailableChapters)
			{
				string verseNumbers = string.Join(",", item.VerseReferences.Select(x => x.Verse));
				
            
            #line default
            #line hidden
            
            #line 403 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
           Write(Html.Raw($"versesForChapter[{item.Chapter.ChapterNumber}] = [{verseNumbers}];"));

            
            #line default
            #line hidden
            
            #line 403 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
                                                                                                ;
			}
		}
		else
		{
			
            
            #line default
            #line hidden
            
            #line 408 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
       Write(Html.Raw("versesForChapter = allQuranVerses;"));

            
            #line default
            #line hidden
            
            #line 408 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
                                                           
		}

            
            #line default
            #line hidden
WriteLiteral(@"
		var navigateVerse = function (delta) {
			var entireList = [];
			Object.keys(versesForChapter).forEach(function (chapterNumber) {
				versesForChapter[chapterNumber].forEach(function (verseNumber) {
					var idToInclude = chapterNumber + ""."" + verseNumber;
					entireList.push(idToInclude);
				});
			});

			var selectedChapter = chapterNumberElement.val() || chapterNumberElement.find(""option"").first().val();
			var selectedVerse = verseNumberElement.val() || verseNumberElement.find(""option"").first().val();
			var currentId = selectedChapter + ""."" + selectedVerse;
			var currentIndex = entireList.indexOf(currentId);
			currentIndex += delta;
			while (currentIndex < 0) {
				currentIndex += entireList.length;
			}
			while (currentIndex >= entireList.length) {
				currentIndex -= entireList.length;
			}
			var newId = entireList[currentIndex];
			window.location.replace('");

            
            #line 432 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
                                Write(Model.Url);

            
            #line default
            #line hidden
WriteLiteral(@"' + newId);
		};

		var chapterNumberChanged = function () {
			selectedChapterNumber = $('#ChapterNumber').val();
			verseNumberElement
				.find('option')
				.remove()
				.end();
			var versesToInclude = versesForChapter[selectedChapterNumber];
			for (var index = 0; index < versesToInclude.length; index++) {
				verseNumberElement.append('<option>' + versesToInclude[index] + '</option>');
			}
			verseNumberElement.val(selectedVerseNumber);
			selectedVerseNumber = null;
		};

		chapterNumberElement.change(chapterNumberChanged);
		chapterNumberElement.val(selectedChapterNumber);
		chapterNumberChanged();

		var selectPreviousVerseNavigateButton = $(""#SelectPreviousVerseNavigateButton"");
		selectPreviousVerseNavigateButton.click(function () { navigateVerse(-1); });

		var selectNextVerseNavigateButton = $(""#SelectNextVerseNavigateButton"");
		selectNextVerseNavigateButton.click(function () { navigateVerse(1); });

		var selectChapterAndVerseNavigateButton = $(""#SelectChapterAndVerseNavigateButton"");
		selectChapterAndVerseNavigateButton.click(function () {
			if (verseNumberElement.val()) {
				var verseReference = chapterNumberElement.val() + '.' + verseNumberElement.val();
				window.location.replace('");

            
            #line 463 "..\..\Views\Shared\SelectChapterAndVerse.cshtml"
                                    Write(Model.Url);

            
            #line default
            #line hidden
WriteLiteral("\' + verseReference);\r\n\t\t\t}\r\n\t\t});\r\n\t})();\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
