<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>QuranX.DocumentModel</RootNamespace>
        <AssemblyName>QuranX.DocumentModel</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <!-- NuGet package references -->
        <PackageReference Include="NLog" Version="6.1.2" />
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
        <!-- Project references -->
        <ProjectReference Include="..\QuranX.Shared\QuranX.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <!-- Resource files -->
        <None Include="Resources\QuranStructure.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="Resources\quran-uthmani.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Properties\Resources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Resources.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Properties\Resources.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

</Project>
