using System.Collections.Generic;

namespace QuranX.DocumentModel;

public static class WordTypes
{
    public static readonly Dictionary<string, string> Values = new()
    {
        ["P"] = "",
        ["DET"] = "",
        ["N"] = "noun",
        ["PN"] = "proper noun",
        ["ADJ"] = "adjective",
        ["PRON"] = "pronoun",
        ["V"] = "verb",
        ["CONJ"] = "conjunction",
        ["REL"] = "relative pronoun",
        ["NEG"] = "negative particle",
        ["INL"] = "Quran initials",
        ["DEM"] = "demonstrative pronoun",
        ["REM"] = "resumption particle",
        ["ACC"] = "accusative particle",
        ["EQ"] = "equalization particle",
        ["CIRC"] = "circumstantial particle",
        ["RES"] = "restriction particle",
        ["T"] = "time adverb",
        ["PRO"] = "prohibition particle",
        ["PREV"] = "preventive particle",
        ["INC"] = "inceptive particle",
        ["SUP"] = "supplemental particle",
        ["AMD"] = "amendment particle",
        ["SUB"] = "subordinating conjunction",
        ["INTG"] = "interrogative",
        ["LOC"] = "location adverb",
        ["COND"] = "conditional particle",
        ["EMPH"] = "emphatic prefix",
        ["VOC"] = "vocative particle",
        ["RSLT"] = "prefixed result particle",
        ["EXL"] = "explanation particle",
        ["EXP"] = "exceptive particle",
        ["CAUS"] = "prefixed particle of cause",
        ["FUT"] = "prefixed future particle",
        ["CERT"] = "particle of certainty",
        ["PRP"] = "prefixed particle of purpose",
        ["ANS"] = "answer particle",
        ["RET"] = "retraction particle",
        ["EXH"] = "exhortation particle",
        ["INT"] = "particle of interpretation",
        ["IMPV"] = "prefixed imperative particle",
        ["COM"] = "prefixed comitative particle",
        ["SUR"] = "surprise particle",
        ["AVR"] = "aversion particle",
        ["IMPN"] = "imperative verbal noun",
    };
}
