#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\VerseCommentary\Index.cshtml"
    using QuranX.Shared.Models;
    
    #line default
    #line hidden
    using QuranX.Web;
    
    #line 1 "..\..\Views\VerseCommentary\Index.cshtml"
    using QuranX.Web.Views.VerseCommentary;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/VerseCommentary/Index.cshtml")]
    public partial class _Views_VerseCommentary_Index_cshtml : System.Web.Mvc.WebViewPage<ViewModel>
    {
        public _Views_VerseCommentary_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\VerseCommentary\Index.cshtml"
  
	var verse = new VerseRangeReference(Model.CommentatorAndCommentary.Commentary.ChapterNumber, Model.CommentatorAndCommentary.Commentary.FirstVerseNumber, Model.CommentatorAndCommentary.Commentary.LastVerseNumber);
	string verseCaption = verse.IsMultipleVerses() ? "verses" : "verse";
	ViewBag.Title = Model.CommentatorAndCommentary.Commentator.Description + $" commentary for {verseCaption} {verse}";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h1>The Quran</h1>\r\n<h2>Verse commentary</h2>\r\n");

            
            #line 12 "..\..\Views\VerseCommentary\Index.cshtml"
Write(Html.Partial("SelectChapterAndVerse", Model.SelectChapterAndVerse));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 13 "..\..\Views\VerseCommentary\Index.cshtml"
Write(Html.Partial("CommentaryView", Model.CommentatorAndCommentary));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
