#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Commentators\Commentators.cshtml"
    using QuranX.Persistence.Models;
    
    #line default
    #line hidden
    using QuranX.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Commentators/Commentators.cshtml")]
    public partial class _Views_Commentators_Commentators_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Commentator>>
    {
        public _Views_Commentators_Commentators_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Commentators\Commentators.cshtml"
  
	ViewBag.Title = "Qur'anic commentators";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h1>");

            
            #line 8 "..\..\Views\Commentators\Commentators.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n<ol");

WriteLiteral(" class=\"commentary__commentator-list striped\"");

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Views\Commentators\Commentators.cshtml"
	
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Commentators\Commentators.cshtml"
     foreach (Commentator commentator in Model)
	{

            
            #line default
            #line hidden
WriteLiteral("\t\t<li>\r\n\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 260), Tuple.Create("\"", 296)
, Tuple.Create(Tuple.Create("", 267), Tuple.Create("/Tafsir/", 267), true)
            
            #line 13 "..\..\Views\Commentators\Commentators.cshtml"
, Tuple.Create(Tuple.Create("", 275), Tuple.Create<System.Object, System.Int32>(commentator.Code
            
            #line default
            #line hidden
, 275), false)
, Tuple.Create(Tuple.Create("", 292), Tuple.Create("/1.1", 292), true)
);

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t\t\t<span");

WriteLiteral(" class=\"col-xs-4 col-sm-3 col-md-2\"");

WriteLiteral(">");

            
            #line 15 "..\..\Views\Commentators\Commentators.cshtml"
                                                        Write(commentator.Code);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\t\t\t\t\t<span");

WriteLiteral(" class=\"col-xs-8 col-sm-9 col-md-10\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\Commentators\Commentators.cshtml"
                                                         Write(commentator.Description);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\t\t\t\t</div>\r\n\t\t\t</a>\r\n\t\t</li>\r\n");

            
            #line 20 "..\..\Views\Commentators\Commentators.cshtml"
	}

            
            #line default
            #line hidden
WriteLiteral("</ol>");

        }
    }
}
#pragma warning restore 1591
