#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
    using QuranX.Persistence.Models;
    
    #line default
    #line hidden
    using QuranX.Web;
    
    #line 2 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
    using QuranX.Web.Views.RootAnalysis;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/RootAnalysis/RootAnalysis.cshtml")]
    public partial class _Views_RootAnalysis_RootAnalysis_cshtml : System.Web.Mvc.WebViewPage<QuranX.Web.Views.RootAnalysis.ViewModel>
    {
        public _Views_RootAnalysis_RootAnalysis_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
  
	ViewBag.Title = $"Verses for root {Model.ArabicRoot} ({Model.RootLetterNames})";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h1>The Qur\'an</h1>\r\n<h2>Verses for root ");

            
            #line 9 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
               Write(Model.ArabicRoot);

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 9 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
                                  Write(Model.RootLetterNames);

            
            #line default
            #line hidden
WriteLiteral(")</h2>\r\n<ul");

WriteLiteral(" class=\"root-analysis__extract-list striped\"");

WriteLiteral(">\r\n\t<li");

WriteLiteral(" class=\"root-analysis__extract-header row hidden-xs\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-sm-4 col-lg-1\"");

WriteLiteral(">Verse</div>\r\n\t\t<div");

WriteLiteral(" class=\"col-sm-4 col-lg-1\"");

WriteLiteral(">Type</div>\r\n\t\t<div");

WriteLiteral(" class=\"col-sm-4 col-lg-1\"");

WriteLiteral(">Transliteration</div>\r\n\t</li>\r\n");

            
            #line 16 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
	
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
     foreach (VerseViewModel extract in Model.Extracts)
	{

            
            #line default
            #line hidden
WriteLiteral("\t\t<li");

WriteLiteral(" class=\"root-analysis__extract row\"");

WriteLiteral(">\r\n\t\t\t<div");

WriteLiteral(" class=\"col-xs-4 col-sm-4 col-lg-1\"");

WriteLiteral(">\r\n\t\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 720), Tuple.Create("\"", 818)
, Tuple.Create(Tuple.Create("", 727), Tuple.Create("/Analysis/", 727), true)
            
            #line 20 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
, Tuple.Create(Tuple.Create("", 737), Tuple.Create<System.Object, System.Int32>(extract.ChapterNumber
            
            #line default
            #line hidden
, 737), false)
, Tuple.Create(Tuple.Create("", 759), Tuple.Create(".", 759), true)
            
            #line 20 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
, Tuple.Create(Tuple.Create("", 760), Tuple.Create<System.Object, System.Int32>(extract.VerseNumber
            
            #line default
            #line hidden
, 760), false)
, Tuple.Create(Tuple.Create("", 780), Tuple.Create("#word_", 780), true)
            
            #line 20 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
     , Tuple.Create(Tuple.Create("", 786), Tuple.Create<System.Object, System.Int32>(extract.SelectedWord.WordNumber
            
            #line default
            #line hidden
, 786), false)
);

WriteLiteral(">\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"verse__reference\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 22 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
                   Write(extract.ChapterNumber);

            
            #line default
            #line hidden
WriteLiteral(".");

            
            #line 22 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
                                          Write(extract.VerseNumber);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</a>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteral(" class=\"col-xs-8 col-sm-4 col-lg-1 small-caps\"");

WriteLiteral(">");

            
            #line 26 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
                                                          Write(extract.SelectedWordPart.Description);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\t\t\t<div");

WriteLiteral(" class=\"col-xs-8 col-sm-push-0 col-sm-3 col-lg-1 small-caps\"");

WriteLiteral(">");

            
            #line 27 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
                                                                        Write(extract.SelectedWord.Buckwalter);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\t\t\t<div");

WriteLiteral(" class=\"col-xs-12 col-sm-12 col-lg-8 root-analysis__extract-text\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"root-analysis__extract-english\"");

WriteLiteral(">\r\n");

            
            #line 30 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
					
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
                     foreach (VerseAnalysisWord word in extract.Words)
					{
						if (word == extract.SelectedWord)
						{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t<strong>");

            
            #line 34 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
                               Write(word.English);

            
            #line default
            #line hidden
WriteLiteral("&nbsp;</strong>\r\n");

            
            #line 35 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
						}
						else
						{
							
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
                       Write(word.English);

            
            #line default
            #line hidden
WriteLiteral("&nbsp;\r\n");

            
            #line 39 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
						}
					}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</li>\r\n");

            
            #line 44 "..\..\Views\RootAnalysis\RootAnalysis.cshtml"
	}

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n");

        }
    }
}
#pragma warning restore 1591
