#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using QuranX.Web;
    
    #line 1 "..\..\Views\CommentariesForVerse\Index.cshtml"
    using QuranX.Web.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CommentariesForVerse/Index.cshtml")]
    public partial class _Views_CommentariesForVerse_Index_cshtml : System.Web.Mvc.WebViewPage<CommentariesForVerse>
    {
        public _Views_CommentariesForVerse_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\CommentariesForVerse\Index.cshtml"
  
	ViewBag.Title = $"Commentaries for {Model.Chapter.ChapterNumber}.{Model.VerseNumber}";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h1>");

            
            #line 8 "..\..\Views\CommentariesForVerse\Index.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");

            
            #line 9 "..\..\Views\CommentariesForVerse\Index.cshtml"
Write(Html.Partial("SelectChapterAndVerse", Model.SelectChapterAndVerse));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\CommentariesForVerse\Index.cshtml"
 foreach (CommentatorAndCommentary commentatorAndCommentary in Model.Commentaries)
{
	
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\CommentariesForVerse\Index.cshtml"
Write(Html.Partial("CommentaryView", commentatorAndCommentary));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\CommentariesForVerse\Index.cshtml"
                                                             
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
