#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using QuranX.Web;
    
    #line 1 "..\..\Views\CommentariesForVerse\Index.cshtml"
    using QuranX.Web.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CommentariesForVerse/Index.cshtml")]
    public partial class _Views_CommentariesForVerse_Index_cshtml : System.Web.Mvc.WebViewPage<CommentariesForVerse>
    {
        public _Views_CommentariesForVerse_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\CommentariesForVerse\Index.cshtml"
  
	ViewBag.Title = $"Commentaries for {Model.Chapter.ChapterNumber}.{Model.VerseNumber}";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h1>The Quran</h1>\r\n<h2>\r\n\tCommentaries for <a");

WriteAttribute("href", Tuple.Create(" href=\"", 201), Tuple.Create("\"", 256)
, Tuple.Create(Tuple.Create("", 208), Tuple.Create("/", 208), true)
            
            #line 10 "..\..\Views\CommentariesForVerse\Index.cshtml"
, Tuple.Create(Tuple.Create("", 209), Tuple.Create<System.Object, System.Int32>(Model.Chapter.ChapterNumber
            
            #line default
            #line hidden
, 209), false)
, Tuple.Create(Tuple.Create("", 237), Tuple.Create(".", 237), true)
            
            #line 10 "..\..\Views\CommentariesForVerse\Index.cshtml"
, Tuple.Create(Tuple.Create("", 238), Tuple.Create<System.Object, System.Int32>(Model.VerseNumber
            
            #line default
            #line hidden
, 238), false)
);

WriteLiteral(">\r\n");

WriteLiteral("\t\t");

            
            #line 11 "..\..\Views\CommentariesForVerse\Index.cshtml"
   Write(Model.Chapter.ChapterNumber);

            
            #line default
            #line hidden
WriteLiteral(".");

            
            #line 11 "..\..\Views\CommentariesForVerse\Index.cshtml"
                                Write(Model.VerseNumber);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</a>\r\n</h2>\r\n<h3>");

            
            #line 14 "..\..\Views\CommentariesForVerse\Index.cshtml"
Write(Model.Chapter.EnglishName);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 14 "..\..\Views\CommentariesForVerse\Index.cshtml"
                            Write(Model.Chapter.ArabicName);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n");

            
            #line 15 "..\..\Views\CommentariesForVerse\Index.cshtml"
Write(Html.Partial("SelectChapterAndVerse", Model.SelectChapterAndVerse));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 16 "..\..\Views\CommentariesForVerse\Index.cshtml"
 foreach (CommentatorAndCommentary commentatorAndCommentary in Model.Commentaries)
{
	
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\CommentariesForVerse\Index.cshtml"
Write(Html.Partial("CommentaryView", commentatorAndCommentary));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\CommentariesForVerse\Index.cshtml"
                                                             
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
